export const predefinedTags = [
  "Social Good",
  "Machine Learning/AI",
  "Education",
  "Low Code/No Code",
  "Web",
  "Blockchain",
  "Productivity",
  "Gaming",
  "Fintech",
  "Mobile",
  "Health",
  "AR/VR",
  "IoT",
  "DevOps",
  "Cybersecurity",
  "Lifehacks",
  "E-commerce/Retail",
  "Language/Translation",
  "Music/Art",
  "Robotics",
  "Quantum",
  "Sustainability",
  "Sports/Fitness",
  "Agriculture",
  "Accessibility",
  "Data Visualization",
  "Space",
  "Supply Chain/Logistics",
  "Jobs/Career",
];
